### ISSUE TITLE
Please provide some example inputs for cf_pypi_releases that kafka-filter-pypi handles

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/pypi-tools#1]
Dear @vitsalis @StefanosChaliasos,

Could you please provide a few example inputs for kafka-filter-pypi on the  cf_pypi_releases topic? I want to get the PyPi/Python pipeline set-up for testing.

Thanks a lot in advance!

**Comment by vitsalis** [comment]
Dear @MagielBruntink ,

Just added testing instructions for testing kafka-filter-pypi on its README. The input coordinates where directly retrieved from the `cf_pypi_releases` topic.

**Comment by MagielBruntink** [comment]
Thank you, this has helped a lot!
