### ISSUE TITLE
Weird behaviour of lazy ingestion of pypi pipeline

### ISSUE THREAD

**Issue by cg122** [fasten-project/pypi-tools#15]
We observed package versions failed in the lazy ingestion. e.g. `Rx:1.0.0`
We checked the log and Kafka topic in our deployment as we can see the message passed to `pycg`, the source code was downloaded successfully to the server, and some errors happened afterwards.
It might relate to the illegal characters (e.g. `<lambda>` expression) in the FASETN uri.
[pycg-issue-lambda-in-fasten-uri.json.gz](https://github.com/fasten-project/pypi-tools/files/10850332/pycg-issue-lambda-in-fasten-uri.json.gz)

**Comment by gdrosos** [comment]
The aforementioned json file indicates that the specific package version was succesfully processed by PyCG. Maybe the issue with the Fasten URI occured in the Metadata Plugin which populates the database. Could you sent me the log of the error?

**Comment by cg122** [comment]
This is the error message stored in Kafka topic:
```
   "error": {
      "stacktrace": "java.lang.IllegalArgumentException: Illegal character in path at index 33: /rx.linq.observable.minby/min_by.<lambda1>()\n\tat java.base/java.net.URI.create(Unknown Source)\n\tat eu.fasten.core.data.FastenPythonURI.create(FastenPythonURI.java:91)\n\tat eu.fasten.core.data.PythonType.<init>(PythonType.java:67)\n\tat eu.fasten.core.data.PartialPythonCallGraph.parseModules(PartialPythonCallGraph.java:100)\n\tat eu.fasten.core.data.PartialPythonCallGraph.getCHAFromJSON(PartialPythonCallGraph.java:84)\n\tat eu.fasten.core.data.PartialPythonCallGraph.<init>(PartialPythonCallGraph.java:69)\n\tat eu.fasten.analyzer.metadataplugin.MetadataDBExtension.getExtendedRevisionCallGraph(MetadataDBExtension.java:230)\n\tat eu.fasten.analyzer.metadataplugin.MetadataDBExtension.consume(MetadataDBExtension.java:123)\n\tat eu.fasten.core.plugins.KafkaPlugin.consume(KafkaPlugin.java:59)\n\tat eu.fasten.server.plugins.kafka.FastenKafkaPlugin.processRecord(FastenKafkaPlugin.java:341)\n\tat eu.fasten.server.plugins.kafka.FastenKafkaPlugin.handleConsuming(FastenKafkaPlugin.java:271)\n\tat eu.fasten.server.plugins.kafka.FastenKafkaPlugin.run(FastenKafkaPlugin.java:168)\n\tat eu.fasten.server.plugins.kafka.FastenKafkaPlugin.start(FastenKafkaPlugin.java:206)\n\tat java.base/java.util.ArrayList.forEach(Unknown Source)\n\tat eu.fasten.server.FastenServer.run(FastenServer.java:202)\n\tat picocli.CommandLine.executeUserObject(CommandLine.java:1919)\n\tat picocli.CommandLine.access$1100(CommandLine.java:145)\n\tat picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)\n\tat picocli.CommandLine$RunLast.handle(CommandLine.java:2326)\n\tat picocli.CommandLine$RunLast.handle(CommandLine.java:2291)\n\tat picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)\n\tat picocli.CommandLine.execute(CommandLine.java:2058)\n\tat eu.fasten.server.FastenServer.main(FastenServer.java:435)\nCaused by: java.net.URISyntaxException: Illegal character in path at index 33: /rx.linq.observable.minby/min_by.<lambda1>()\n\tat java.base/java.net.URI$Parser.fail(Unknown Source)\n\tat java.base/java.net.URI$Parser.checkChars(Unknown Source)\n\tat java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)\n\tat java.base/java.net.URI$Parser.parse(Unknown Source)\n\tat java.base/java.net.URI.<init>(Unknown Source)\n\t... 23 more\n",
      "type": "java.lang.IllegalArgumentException",
      "message": "Illegal character in path at index 33: /rx.linq.observable.minby/min_by.<lambda1>()"
   },
```

**Comment by MagielBruntink** [comment]
Please have a look at the lines 5683, 6377, and 7055, of the pycg call graph. One case looks like the following:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3635696/221959605-f84a0eae-0f6d-4695-9adf-70eec8517122.png">

There is `<lambda1>` there in the namespace field that causes the issue. Indeed the problem occurs when the metadata plugin tries to process this call graph. Is the `<lambda1>` intended output? If yes, then probably the metadata plugin needs to be adjusted.

**Comment by gdrosos** [comment]
With a little search I found out that the `<lambda1>` is the intended output, as PyCG supports calls from lambda functions (see this [minimal example use case](https://github.com/vitsalis/PyCG/tree/master/micro-benchmark/snippets/lambdas/call)). The uri of each such function is represented by `<lambda`+ an auto-incrementing number of the lambda in the specific scope of the function. 

It seems that the current Fasten URI which is used in the metadata plugin does not support the `<>` symbols. Therefore a sollution could be to extend the FastenURI class to support those special characters.

**Comment by cg122** [comment]
It seems this once worked on public fasten service. 
https://api.fasten-project.eu/api/pypi/packages/Rx/1.0.0/callables?limit=1000
https://api.fasten-project.eu/api/pypi/packages/Rx/1.0.0/rcg
The special characters (`<>`) are encoded, e.g .` "fasten_uri": "/rx.linq.observable.minby/min_by.%3Clambda1%3E()"`, `"680": {"namespace": "/rx.linq.observable.groupjoin/group_join.subscribe.%3Clambda1%3E()"`

**Comment by MagielBruntink** [comment]
I am working on a fix for this - will tag you in the PR.
