### ISSUE TITLE
This call to /usr/bin/time is not very portable, doesn't run on eg. Windows.

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/pypi-tools#7]
https://github.com/fasten-project/pypi-tools/blob/5cd171d07ffdbb1c18c4e818d3ca22191ec1dd9e/cg-producer/pycg_producer/producer.py#L241

**Comment by gdrosos** [comment]
Hello @MagielBruntink, thanks for reporting the issue. I managed to calculate the time in a way that supports cross-platforms but for the maximum resident set size of the subprocess command I could not find a cross-platform sollution. In my opinion, we have two options: Either remove the `max_rss` attribute from the ercgs or we could avoid calulating this metric on windows platforms.

**Comment by MagielBruntink** [comment]
This Python package can do it I think: https://github.com/giampaolo/psutil

**Comment by gdrosos** [comment]
Yes, I tried using this library but it returns the max_rss of the whole runnnig program whereas we previously calculated the  max_rss  only out of pycg's execution, but I will look at it in more detail, thanks!

**Comment by MagielBruntink** [comment]
This one seems simple and portable: https://pypi.org/project/cmdbench/
