### ISSUE TITLE
Missing cmdbench module

### ISSUE THREAD

**Issue by amottier** [fasten-project/pypi-tools#9]
I tried to run `cg-producer` Docker image version `a6e779a3` and got the following error:
```
ModuleNotFoundError: No module named 'cmdbench'
```

It seems that [cg-producer/setup.py](https://github.com/fasten-project/pypi-tools/blob/main/cg-producer/setup.py#L22) should have installed it, but looking at the [`Dockerfile`](https://github.com/fasten-project/pypi-tools/blob/main/cg-producer/Dockerfile) it seems that only `setup.py` of pycg is actually executed.

**Comment by MagielBruntink** [comment]
On the monster deployment this issue crashes the pycg deployment:
```
/scp:magiel@monster.ewi.tudelft.nl:~/fasten-k8s-deployments/fasten/pypi-cg-producer $ kubectl logs pycg-6b576b586d-464l2 -n fasten
Traceback (most recent call last):
  File "/cggen/entrypoint.py", line 28, in <module>
    from pycg_producer.producer import CallGraphGenerator
  File "/cggen/pycg_producer/producer.py", line 29, in <module>
    import cmdbench
ModuleNotFoundError: No module named 'cmdbench'
```
